### ISSUE TITLE
can you release the train code and inference demo code?

### ISSUE THREAD

**Issue by ctgushiwei** [TuSimple/RangeDet#1]

**Comment by Abyssaledge** [comment]
Codes will be released once the virtual conference is over (middle of October).

**Comment by ShuoLiu-Max** [comment]
can you release the train code and inference demo code?

**Comment by abbyxxn** [comment]
> can you release the train code and inference demo code?



> can you release the code since the virtual conference is over

Sorry for the delay, we are doing the final peer review. We’re gonna release the code as soon as possible, in early November. Please wait for a few more days.
