### ISSUE TITLE
Regarding the normalization of data and the coordinates of the Meta-Kernel input data.

### ISSUE THREAD

**Issue by MaxChanger** [TuSimple/RangeDet#10]
Hello, 
I am trying to understand the coordinate system which the data inputed into the Meta-Kernel module belongs, such as `x,y,z,range`. As reported in Table 2 for the performance comparison of different inputs, does `x,y,z` belong to the LiDAR coordinate system?

The reason for this question is because I saw that `NormData(NormDataParam)` was executed on the data in the code.  For `range_value, intensity,elongation,pc_vehicle_frame_x,pc_vehicle_frame_y,pc_vehicle_frame_z,inclination,azimuth`, the `(inputdata-mean)/std` operation has been performed.

Below is my understanding, `pc_vehicle_frame_x, y, z` can be considered as the `x,y,z` information read from the LiDAR pcd file, that is, the point cloud in the vehicle-mounted LiDAR coordinate system. And then, using the statistically significant average value `mean, std` of the entire data set to normalize `x,y,z`, that is, the normalized data is directly input to the Meta-Kernel data instead of the original xyz point cloud data? In addition, I’m not sure if there are other operations that handle coordinates

I don’t know if my understanding is correct, could you give me some hints.

**Comment by Abyssaledge** [comment]
Thanks for sharing your understanding, which is correct. Meta-kernel takes the normalized `x,y,z` of LiDAR coordinate system as input. BTW, if I remember correctly, it's also OK to use the unnormalized original `x,y,z`.

**Comment by MaxChanger** [comment]
Okay, thank you very much for your quick reply!
