### ISSUE TITLE
Question about Meta-kernel

### ISSUE THREAD

**Issue by Solacex** [TuSimple/RangeDet#13]
Hello,

First, thanks for your inspiring work. 
As I could not find a clear definition of ``coord'' in the meta-kernel. I want to know the coordinate for computing relative coordinates are normalized or not?

**Comment by Solacex** [comment]
Hello,

I think the rough mean/std should be:

  'pc_vehicle_frame_x': (1.5672500e+00, 3.0740625e+02),
  'pc_vehicle_frame_y': (9.8824875e-01, 2.1913250e+02),
  'pc_vehicle_frame_z': (1.4, 1.0),

I want to know more details about this:
1) How do you estimate and get them?
2) Have you tried to use unnormed xyz for self.mlps? Will this leads to obvious change? 
3) Will this mean/std influence the final performance a lot?

**Comment by Abyssaledge** [comment]
1. For x and y, we calculate the std and mean over thousands of example. For z, we just set it intuitively when developing.
2. I have tried it long time ago in a toy experiment which does not lead to obvious change. But I can guarantee the performances on more extensive experiments. I recommend to use the normalized one.
3. I do not think it has significant influence on performances, but it seems to be a good choice to use precise mean/std.

**Comment by Solacex** [comment]
Thanks for your prompt reply, it really helps!

**Comment by abbyxxn** [comment]
> Hello,
> 
> I think the rough mean/std should be:
> 
> 'pc_vehicle_frame_x': (1.5672500e+00, 3.0740625e+02), 'pc_vehicle_frame_y': (9.8824875e-01, 2.1913250e+02), 'pc_vehicle_frame_z': (1.4, 1.0),
> 
> I want to know more details about this:
> 
> 1. How do you estimate and get them?
> 2. Have you tried to use unnormed xyz for self.mlps? Will this leads to obvious change?
> 3. Will this mean/std influence the final performance a lot?

About your second question, we started our experiments with the unnormalized xyz for `self.mlps`, but in the process of improving the meta-kernel operator, it was replaced with the normalized xyz. In our experiment, from my memory, both worked about the same. Some cases, I think it is ok to try unnormalized coordinates.

**Comment by Solacex** [comment]
> > Hello,
> > I think the rough mean/std should be:
> > 'pc_vehicle_frame_x': (1.5672500e+00, 3.0740625e+02), 'pc_vehicle_frame_y': (9.8824875e-01, 2.1913250e+02), 'pc_vehicle_frame_z': (1.4, 1.0),
> > I want to know more details about this:
> > 
> > 1. How do you estimate and get them?
> > 2. Have you tried to use unnormed xyz for self.mlps? Will this leads to obvious change?
> > 3. Will this mean/std influence the final performance a lot?
> 
> About your second question, we started our experiments with the unnormalized xyz for `self.mlps`, but in the process of improving the meta-kernel operator, it was replaced with the normalized xyz. In our experiment, from my memory, both worked about the same. Some cases, I think it is ok to try unnormalized coordinates.

Thanks for your response! 
By far, in my experiments, they show very different results and I am trying to figure it out.

**Comment by Solacex** [comment]
> 1. For x and y, we calculate the std and mean over thousands of example. For z, we just set it intuitively when developing.
> 2. I have tried it long time ago in a toy experiment which does not lead to obvious change. But I can NOT guarantee the performances on more extensive experiments. I recommend to use the normalized one.
> 3. I do not think it has significant influence on performances, but it seems to be a good choice to use precise mean/std.

Besides, is there any further explanation for the mean/std for the z axis?
