### ISSUE TITLE
About the installation errors

### ISSUE THREAD

**Issue by Tingla** [TuSimple/RangeDet#14]
Hi, Could kindly help me on the below issues  when I perform installation command : pip install -v -e .
I have successfully install mxnet 2.0 and dependence:
The error log is in attachment.(I did not change the source code)
Thank you very much!

[temp.txt](https://github.com/TuSimple/RangeDet/files/8091686/temp.txt)

**Comment by Abyssaledge** [comment]
Thanks for using! 
Do you have `pybind11` and `eigen` installed?

**Comment by abbyxxn** [comment]
> 
I think the error may be that the C++ was not compiled with the correct link to Eigen.

**Comment by Abyssaledge** [comment]
@Tingla If your issue has not been solved yet, I suggest you write a snippet of  pybind code using eigen to check if your installation is right.

**Comment by Tingla** [comment]
@Abyssaledge @abbyxxn Sorry for late reply, very appreciate your help!!!  It is my bad. I have not using "--recursive" to include sub module.....
Now everything goes smoothly.
BTW, did Tusimple using pure range view image method like rangedet or combined/fusion with BEV method(eg point pilar)?

**Comment by Abyssaledge** [comment]
@Tingla  Thanks for your feedback.
Although I cannot tell you the details, we did use the range view in our applications.
