### ISSUE TITLE
Docker image for installation

### ISSUE THREAD

**Issue by ShrutheeshIR** [TuSimple/RangeDet#20]
Hello. 
This work introduced here is fantastic and I'd like to try it out. However, I have trouble with installation at different stages, with `CUDA` mismatch, `pybind11` etc. I was wondering if you have a docker image that one can use to test and run the module? Thanks

**Comment by Abyssaledge** [comment]
Sorry I do not have enough resources to maintain this project now, so I cannot provide a docker. But the good news is we are transferring the code to PyTorch, and that will be much more easy to use.

**Comment by ShrutheeshIR** [comment]
Thanks, looking forward to it

**Comment by tchittesh** [comment]
Is there any timeline as to when the PyTorch code will be made available? I'm trying to decide whether to wait for that, or transcribe some code I already have from PyTorch to Tensorflow to use with this repo.
