### ISSUE TITLE
PyTorch code

### ISSUE THREAD

**Issue by tchittesh** [TuSimple/RangeDet#21]
Is there any timeline or estimate as to when the PyTorch code will be made available? I'm trying to decide whether to wait for that, or transcribe some code I already have from PyTorch to Tensorflow to use with this repo.

**Comment by Abyssaledge** [comment]
Thanks for your interest! It will take much effort and many resources to align the implementations based on two totally different framework, and the code release also depends on the publication of our improved method. Thus we can not promise the date of release. Sorry for the inconvenience.
