### ISSUE TITLE
Questions about meta-kernel.

### ISSUE THREAD

**Issue by jikerWRN** [TuSimple/RangeDet#3]
Thanks for your good work and open source code!

When I read the paper and code, I have a question.
In Meta-Kernel convolution, if we remove element-wise product operation, does Meta-Kernel convolution become standard convolution?

Looking forward to your reply!

**Comment by Abyssaledge** [comment]
Thanks for your attention.
Good question!  Yes, you are right. 
By the way, the key point of meta-kernel is the weight generation from meta-information. It makes a big difference. We adopt the element-wise product because of its efficiency.
@jikerWRN

**Comment by jikerWRN** [comment]
Ok, thanks for your reply!
