### ISSUE TITLE
Can you provide the supplementary material？

### ISSUE THREAD

**Issue by jikerWRN** [TuSimple/RangeDet#4]
Hi, can you provide the supplementary material of the paper? Thanks!

**Comment by Abyssaledge** [comment]
https://openaccess.thecvf.com/content/ICCV2021/supplemental/Fan_RangeDet_In_Defense_ICCV_2021_supplemental.pdf
Also updated in README.md

**Comment by jikerWRN** [comment]
Ok, thanks!
