### ISSUE TITLE
Results on KITTI

### ISSUE THREAD

**Issue by turboxin** [TuSimple/RangeDet#7]
Hi, thanks for opensourcing this great work.

I'm wondering the results on KITTI dataset, did you do experiments on it?  

Thanks a lot!

**Comment by Abyssaledge** [comment]
Table 10 in https://openaccess.thecvf.com/content/ICCV2021/papers/Fan_RangeDet_In_Defense_of_Range_View_for_LiDAR-Based_3D_Object_ICCV_2021_paper.pdf
or http://www.cvlibs.net/datasets/kitti/eval_object_detail.php?&result=f6033db4d43b5c7866751edc687c13b286c2ae95

**Comment by turboxin** [comment]
Thanks @Abyssaledge, I read the original arxiv paper without KITTI results. Closing this issue.

**Comment by Abyssaledge** [comment]
BTW, the result in KITTI is not so well, because the range-based detection depends on large dataset.

**Comment by turboxin** [comment]
I see~ Thanks for the reminding!
