### ISSUE TITLE
Questions about mixed precision?

### ISSUE THREAD

**Issue by jikerWRN** [TuSimple/RangeDet#8]
Hi, 

I found that the meta-kernel consumes a lot of memory. Using mixed-precision training should alleviate this problem. I want to ask whether using mixed-precision training will affect the algorithm's performance? Can only float16 be used in meta-kernel during training?

Thanks!

**Comment by Abyssaledge** [comment]
Thanks for using! All of our experiments are conducted with mixed-precision training due to the memory limit of our devices (11GB). So don't worry, I believe there is no problem even if you enable float16 in all components.

**Comment by jikerWRN** [comment]
Thanks for your reply, I got it. However, just for discussion, can we use float16 only in a part of the network? Do you have any experience for share? Thanks!

**Comment by Abyssaledge** [comment]
Yes, you can. In fact, the loss functions are calculated in fp32 mode. You can call `to_fp32()` or `to_fp16()` anywhere to cast the data type, as long as you enable fp16 mode in the config. 
Examples: https://github.com/TuSimple/RangeDet/blob/cd560c9d7f6b8ae932fdba8a00f95a66de9f2fe3/rangedet/symbol/head/builder.py#L258

https://github.com/TuSimple/RangeDet/blob/main/config/rangedet/rangedet_veh_wo_aug_all_36e.py#L35

**Comment by jikerWRN** [comment]
Ok, thanks!
