### ISSUE TITLE
how to calculate NormDataParam

### ISSUE THREAD

**Issue by IAS-01** [TuSimple/RangeDet#9]
how to calculate NormDataParam when I change the Datasets to other ?

**Comment by Abyssaledge** [comment]
It is same as the way in calculating the mean and std of RGB channels in image-based dataset.

**Comment by abbyxxn** [comment]
When you change the dataset, there are two parameters to be statistics here: Mean and Standard Deviation. In the first loop add up all the values and divide by their total amount. In the second loop, each number needs to subtract the Mean and square the result. Then work out the mean of those squared differences. Take the square root of that.

> how to calculate NormDataParam when I change the Datasets to other ?
